name: Run Execution Tests
on: [ pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Execute CMake Tests
        uses: threeal/cmake-action@v1.3.0
        run: cxx-compiler